
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Shared/Navbar";
import Footer from "../components/Shared/Footer";
import HorizontalScrollWrapper from "../components/HorizontalScrollWrapper"; // Import the client component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VICIO",
  description: "Generated by create next app",
  icons:{
    icon: ['/favicon_io/favicon.ico?v=4'],
    apple: ['/favicon_io/apple-touch-icon.png?v=4'],
    shortcut: ['/favicon_io/apple-touch-icon.png']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} no-scrollbar`}>
        <Navbar />
        <HorizontalScrollWrapper>
          {children}
        </HorizontalScrollWrapper>
        <Footer />
      </body>
    </html>
  );
}


